### ISSUE TITLE
Question about original thermostat software

### ISSUE THREAD

**Issue by geekcoding007** [diyless/opentherm-thermostat#1]
First of all, Keep up the good work!

Is it possible to put on the original file witch contains the original thermostat webpage? (witch also contains the PID settings OT settings and MQTT settings) i made a mistake and erased it accidentally from the ESP board.

**Comment by diyless** [comment]
Hi @geekcoding007 
Do you mean the original firmware?

**Comment by diyless** [comment]
You can re-flash the original firmware using web flasher https://diyless.com/flasher
Activation code is not required for registered devices.

**Comment by geekcoding007** [comment]
Hi @diyless thank you! that was exactly what i needed.

this flasher site comes in very handy if you screw up your firmware 😆 

got the board up and running again 👍.
